name: marp-build-and-deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Baixa o tema e coloca em themes/
      - name: Get theme from raw.github
        run: |
          mkdir -p themes
          curl -L -o themes/barbosa.css \
            https://raw.githubusercontent.com/dvanael/marp-barbosa/refs/heads/main/theme/barbosa.css

      # Diretórios de saída
      - name: Ensure build dirs
        run: |
          mkdir -p build
          mkdir -p build/fichamento

      # Copia imagens se existirem
      - name: Copy images for slides
        run: if [[ -d slides/img ]]; then cp -R slides/img build/img; fi

      - name: Copy images for fichamento
        run: if [[ -d fichamento/img ]]; then cp -R fichamento/img build/fichamento/img; fi

      - name: Marp Build HTML (slides)
        uses: docker://marpteam/marp-cli:v4.1.1
        with:
          args: -I slides/ -o build/ --set-theme themes/barbosa.css
        env:
          MARP_USER: root:root

      - name: Marp Build HTML (fichamento)
        uses: docker://marpteam/marp-cli:v4.1.1
        with:
          args: -I fichamento/ -o build/fichamento --set-theme themes/barbosa.css
        env:
          MARP_USER: root:root

      - name: Marp Build PDF (slides)
        uses: docker://marpteam/marp-cli:v4.1.1
        with:
          args: --pdf --pdf-outlines -I slides/ -o build/ --set-theme themes/barbosa.css
        env:
          MARP_USER: root:root

      - name: Marp Build PDF (fichamento)
        uses: docker://marpteam/marp-cli:v4.1.1
        with:
          args: --pdf --pdf-outlines -I fichamento/ -o build/fichamento --set-theme themes/barbosa.css
        env:
          MARP_USER: root:root

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
